homeassistant:


  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 98
  unit_system: metric
  time_zone: America/Toronto

  customize: !include customize.yaml


frontend: !include frontend.yaml
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true


duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.

recorder:
  purge_interval: 0

history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#iphone app
ios:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key
      mac : !secret xiaomi_mac
      host: !secret xiaomi_host

#https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW
#https://community.home-assistant.io/t/making-aeotec-z-wave-stick-static/3716/4 <- Symblink + trick pour la led qui flash
zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    light.atelier:
      expose: true
    light.bureau:
      expose: true
    light.level_4:
      expose: true
      name: Couloir
    light.level_2:
      expose: true
      name: Ilot
    light.level_3:
      expose: true
      name: Lavabo
    light.level:
      expose: true
      name: Miroir
    light.chambre:
      expose: true
    light.chevets:
      expose: true
    light.coralie:
      expose: true
    light.escalier:
      expose: true
    light.exterieur_balcon:
      expose: true
      name: Balcon
    light.entree_in:
      expose: true
      name: Entrée Intérieur
    light.entree_out:
      expose: true
      name: Entrée Extérieur
    light.exterieur_coin:
      expose: true
      name: Stationnement
    light.jumeaux:
      expose: true
      name: Chambre des gars
      aliases: 
        - Félix
        - Xavier
        - des Jumeaux
    light.lampadaire:
      expose: true
    light.laveusesecheuse:
      expose: true
      name: Laveuse Sécheuse
      aliases:
        - Bas des escaliers
    light.salon:
      expose: true
    light.cuisine:
      expose: true
      name: table
    light.solarium:
      expose: true
    group.cuisine_lights:
      expose: true
      name: cuisine
    group.salle_jeux:
      expose: true
      name: Salle de jeux

# Text to speech
tts:
  - platform: google
    language: 'fr'

  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    #profile_name: AWS_PROFILE
    region_name: 'us-east-1'
    voice: Chantal

hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: true
      filename: phue.conf

mqtt:
  broker: !secret mqtt_broker
  port: 1883


# Cloud
#cloud:

camera: !include cam.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml

media_player: !include media_player.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
shell_command: !include shell_command.yaml
switch: !include switches.yaml
light: !include lights.yaml
climate: !include climate.yaml
group: !include groups.yaml
scene: !include scene.yaml
automation: !include automations.yaml
script: !include scripts.yaml
